name: simbucore
description: Cross project code to support flutter application development

version: 0.0.1

environment:
  sdk: ">=2.18.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter

  test: any
  
  # Parses raw command-line arguments into a set of options and values.
  args: ^2.3.0

  # A simple Event Bus using Dart Streams for decoupling applications.
  event_bus:

  # Get current device information from within the Flutter application.
  device_info_plus:

  # A fully featured Gherkin parser and test runner. Works with Flutter and Dart 2.
  #
  # This implementation of the Gherkin tries to follow as closely as possible
  # other implementations of Gherkin and specifically Cucumber in it's various forms.
  # flutter_gherkin:
  # Using pre-release as it uses the new integration_test that is replacing the flutter_driver package.
  flutter_gherkin: ^3.0.0-rc.17

  # A fully featured Gherkin parser and test runner.
  gherkin:

  # A reactive state caching and data-binding framework
  # Recommend replacement for provider: that is mentioned by flutter
  # https://docs.flutter.dev/development/data-and-backend/state-mgmt/options
  hooks_riverpod: ^1.0.3+1

  # Extended date/time methods
  intl:

  # Small, easy to use and extensible logger which prints beautiful logs.
  logger:

  # With this plugin you can perform platform detection on all platforms, including Web, without errors.
  universal_platform:

  # Detects the current browser and version of the browser.
  web_browser_detect:

dev_dependencies:

  # automatically organize your dart imports
  import_sorter:

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - test/integration_test/report/fixture/unformatted_json_report.json
    
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
